### ISSUE TITLE
Blocks Have No Hardness Or Sound

### ISSUE THREAD

**Issue by ChloeDawn** [Corosauce/DesirePaths#1]
The blocks added by the mod can be broken instantly in survival mode, and sound like stone blocks rather than grass.

**Mod version:** [1.12.1-1.0](https://minecraft.curseforge.com/projects/desirepaths/files/2639420)

**Comment by Corosauce** [comment]
:+1: went with dirt sound instead of grass, good enough for me!

https://github.com/Corosauce/DesirePaths/commit/898f3bdfec7eeb3b189fd657dacb25537484f12f
