### ISSUE TITLE
[Suggestion] Descriptive names.

### ISSUE THREAD

**Issue by Tokeli** [Corosauce/DesirePaths#12]
'Worn Grass 1', 'Worn Grass 2' are sort of bland names!

1. Trampled Grass
2. Slightly Worn Grass
3. Worn Grass
4. Very Worn Grass
5. Patches of Grass
6. Bare Dirt

Or something along those lines!

**Comment by Corosauce** [comment]
A good idea, I like it.

**Comment by Corosauce** [comment]
Couldn't think of any better names, just went with those for now :+1: 
https://github.com/Corosauce/DesirePathas/commit/85efa4cfcb00375bc4d777520535db3f4f098f0c
