### ISSUE TITLE
Item Models Not Colored

### ISSUE THREAD

**Issue by ChloeDawn** [Corosauce/DesirePaths#2]
The item models have grey grass on them - they are missing IItemColor bindings.

**Mod version:** [1.12.1-1.0](https://minecraft.curseforge.com/projects/desirepaths/files/2639420)

**Comment by Corosauce** [comment]
:+1: 

https://github.com/Corosauce/DesirePaths/commit/65fa752dec3bd48909e3de14c1462b8a35124503
