### ISSUE TITLE
[FEATURE] Grass to dirt and back

### ISSUE THREAD

**Issue by V10lator** [Corosauce/DesirePaths#3]
I think it would be a good idea to wear the grass slowly to a dirt block, then exchange vanillas dirt to grass algo with the one from DesirePaths.

**Comment by Corosauce** [comment]
This is partially originally how I had it, looks too ugly when vanilla changes a vanilla dirt block all the way to vanilla grass block without any gradual repair and those blocks are mixed in with still partially trampled grass.

**Comment by Corosauce** [comment]
I might have originally misunderstood your meaning of "exchange vanillas dirt to grass algo", but re-reading it now I realize what you mean. Doing that would be a pain and require a coremod, not interested in going that route, also just added a config so you can make the final worn stage be any block you want. https://github.com/Corosauce/DesirePaths/commit/1fcb63cc937e7a60f3a852f9888428cc4984fa32
