### ISSUE TITLE
[Suggestion]  Remove tall_grass, double_grass

### ISSUE THREAD

**Issue by bc-hill** [Corosauce/DesirePaths#9]
I'd love to see tall grass be removed as the path wears down.  I guess it couldn't really grow back, but removal would still be cool.  Having a double grass in the middle of a path looks odd.
Thank you!

**Comment by Corosauce** [comment]
It should be already, I wrote code for it, but maybe I'm only doing tall_grass and not double_grass, I'll check up on that. Also I have code in place to give it a random chance to place tallgrass when the path becomes fully restored, might add double grass there too.

**Comment by bc-hill** [comment]
Sorry.  Have spent some time jumping on grass, and confirmed that it is already implemented.
